# Generated by Django 3.1.1 on 2020-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivtests', '0002_tests_picked_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
